//
// Created by fakhr on 12.02.20.
//

#ifndef SPARQL_QUERY_SELECTQUERYRESULT_HPP
#define SPARQL_QUERY_SELECTQUERYRESULT_HPP

class SelectQueryResult
{

};

#endif //SPARQL_QUERY_SELECTQUERYRESULT_HPP
